#
# Makefile
#
# juste for testing
#


ext: ext.c
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -o ext ext.c -lm

test: test.c
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -o test test.c -lm
block: block.c
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -o block block.c -lm
